micronaut:
  application:
    name: railRoadOperations
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:3000
netty:
  default:
    allocator:
      max-order: 3
